apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: 640168414967.dkr.ecr.us-east-1.amazonaws.com/backend:v86
          imagePullPolicy: Always
          ports:
            - containerPort: 7001
          resources:
            requests:
              memory: "512Mi" # Minimum memory requested
              cpu: "500m" # Minimum CPU requested (500 millicores)
            limits:
              memory: "1Gi" # Maximum memory allowed
              cpu: "1"

---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 7001
      targetPort: 7001
      # nodePort: 30001
  type: ClusterIP
