apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
        - name: mongo
          image: 640168414967.dkr.ecr.us-east-1.amazonaws.com/mongo
          imagePullPolicy: Never
          ports:
            - containerPort: 27017
          resources:
            requests:
              memory: "512Mi" # Minimum memory requested
              cpu: "500m" # Minimum CPU requested (500 millicores)
            limits:
              memory: "1Gi" # Maximum memory allowed
              cpu: "1"

---
apiVersion: v1
kind: Service
metadata:
  name: mongo-service
spec:
  selector:
    app: mongo
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
  type: ClusterIP
