apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      imagePullSecrets:
        - name: ecr-secret
      containers:
        - name: frontend
          image: 640168414967.dkr.ecr.us-east-1.amazonaws.com/mern-deployment
          imagePullPolicy: Never
          ports:
            - containerPort: 5173
          resources:
            requests:
              memory: "512Mi" # Minimum memory requested
              cpu: "500m" # Minimum CPU requested (500 millicores)
            limits:
              memory: "1Gi" # Maximum memory allowed
              cpu: "1"

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5173
      nodePort: 30002
  type: LoadBalancer
